# Generated by Django 3.2.25 on 2024-03-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_name', models.CharField(max_length=100)),
                ('victories', models.IntegerField(default=0)),
                ('defeats', models.IntegerField(default=0)),
                ('center_army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_army', to='Soldiers.armytype')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soldiers.faction')),
                ('left_army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_army', to='Soldiers.armytype')),
                ('right_army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_army', to='Soldiers.armytype')),
            ],
        ),
    ]
